services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8001:8001"
    command: python main.py
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: main_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"

volumes:
  postgres_data: